# docker-compose.yml
version: '3.6'
services:
  ocotbercms_web:
    image: aspendigital/octobercms
    init: true

    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql #DB_HOST should match the service name of the database container
      - DB_DATABASE=octobercms
      - DB_USERNAME=root
      - DB_PASSWORD=root
    ports:
      - 8090:80
    volumes:
      - ./october/.env:/var/www/html/.env
      - ./october/plugins:/var/www/html/plugins
      - ./october/storage/app:/var/www/html/storage/app:rw
      - ./october/themes/em.com:/var/www/html/themes/em.com
      

      
    depends_on:
      - ocotbercms_db

  ocotbercms_db:
    image: mysql:5.7
    # restart: always
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=octobercms
    volumes:
      - ocotbercms_db:/var/lib/mysql


volumes:
  ocotbercms_web:
  ocotbercms_db: